#!/bin/bash

# Copyright (C) 2011 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

get() {
  urlbase=$1
  filename=$2
  algorithm=$3
  checksum=$4
  echo "fetching $urlbase$filename"
  curl -s -o $filename $urlbase$filename
  ${algorithm}sum $filename
  ${algorithm}sum -c - <<EOF
$checksum  $filename
EOF
}

# When updating this, also update the version number in build.properties
# and on http://code.google.com/p/walkaround/wiki/RunningTheCode .
version=1.6.1
checksum=8c2a88b05bddcba7bca51e272f7e10363039f48e

mkdir -p appengine-sdk
cd appengine-sdk
get http://googleappengine.googlecode.com/files/ appengine-java-sdk-$version.zip sha1 $checksum
unzip -q appengine-java-sdk-$version.zip
