#!/bin/bash

# Copyright (C) 2011 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

get() {
  urlbase=$1
  filename=$2
  algorithm=$3
  checksum=$4
  echo "fetching $urlbase$filename"
  curl -s -o $filename $urlbase$filename
  ${algorithm}sum $filename
  ${algorithm}sum -c <<EOF
$checksum  $filename
EOF
}

mkdir -p appengine-sdk
cd appengine-sdk
get http://googleappengine.googlecode.com/files/ appengine-java-sdk-1.5.5.zip sha1 8bf3aecd400ee57679417a03a68c4409c05e953c
unzip -q appengine-java-sdk-1.5.5.zip
